### ISSUE TITLE
SwiftShader

### ISSUE THREAD

**Issue by GFOXSH** [gamethich2020/DirectX-ExaGear#3]
So... I can offer an alternative to WineD3D's Direct3D 9 software render. Is TransGaming SwiftShader. Check for my repository https://github.com/GFOXSH/swiftshader

**Comment by GFOXSH** [comment]
And you can add https://github.com/GFOXSH/D3D8toD3D9shim to add Direct3D 8 support to SwiftShader.

**Comment by seisdr** [comment]
isn't the opengl32.dll is the important part

**Comment by seisdr** [comment]
bro how do I use that ? 
I followed what he doing in this video and it didn't work obviously because I need the opengl32.dll beside d3d9.dll has a different size 
![Screenshot_2020-06-14-13-09-22](https://user-images.githubusercontent.com/45742462/84590604-b5d50d00-ae40-11ea-83d2-f41330bb95cf.png)

**Comment by seisdr** [comment]
I might figured out how it works but it doesn't work I having an issue 

![Screenshot_2020-06-15-04-43-26](https://user-images.githubusercontent.com/45742462/84610658-080b4200-aec4-11ea-816f-1faff323a659.png)
after I click on ok the screen is freezing and I see the swiftshader configure file on my home directory and when I open the website http://localhost:8080/swiftconfig
I see 0 fps and 0 frame and screen kept freeze
![Screenshot_2020-06-15-04-41-10](https://user-images.githubusercontent.com/45742462/84610720-456fcf80-aec4-11ea-8f02-2e732b7aaecd.png)

**Comment by gamethich2020** [comment]
OpenGL mod files obb all how?

**Comment by seisdr** [comment]
> OpenGL mod files obb all how?

speak in your language
